[package]
name = "crmps"
version = "0.1.0"
authors = ["Muiz"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
zip = "0.5.5"
zip-extensions = "0.5.0"